basic_settings:
  site_title: 
  site_tagline: 
  favicon_image: /images/favicon.png

header_settings:
  avatar_image: /images/Glogo512x512.png
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Articles'
      url: '/blog'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/f/xnqkyzyv'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/glennbroadway'
  twitter_url: 'https://twitter.com/glennbroadway'
  instagram_url: 'https://instagram.com/glennbroadway'
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/c/GlennBroadway'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/glennbroadway/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#4D4D4A'
  text_light_color: '#ABB7B7'
  accent_color: '#03CBDC'
  border_color: '#03CBDC'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  # font_embed: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600" rel="stylesheet">'
  font_embed: '<link rel="stylesheet" href="https://use.typekit.net/phf2yqq.css">'
  # title_font: '"Nunito", sans-serif'
  # body_font: '"Nunito", sans-serif'
  # regular_weight: 400
  # bold_weight: 600
  title_font: '"degular", sans-serif'
  body_font: '"aktiv-grotesk", sans-serif'
  font-weight: 300;
  font-style: normal;
  regular_weight: 300
  bold_weight: 600
  site_title:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 20
    medium_size: 24
    large_size: 27
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: 0
    line_height: 1.2
  h2:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: 0
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 300
    letter_spacing: 0
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 17
    medium_size: 21
    large_size: 24
    weight: 300
    letter_spacing: 0
    line_height: 1.4
  blockquote:
    small_size: 20
    medium_size: 25
    large_size: 35
    weight: 300
    letter_spacing: -0.02
    line_height: 1.2
  buttons:
    weight: 600
    letter_spacing: 0.03

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""